# Generated by Django 4.1 on 2023-09-13 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
